#!/usr/bin/python3
def raise_exception(x):
    return
